paths:
  - /_bulk
  - /_search
  - /{index}/_bulk
  - /{index}/_create/{id}
  - /{index}/_doc
  - /{index}/_doc/{id}
  - /{index}/_explain/{id}
  - /{index}/_search
  - /{index}/_source/{id}
  - /{index}/_update/{id}
