#!/usr/bin/env python3
"""
Generate __init__.py files for OpenSearch Protobufs Python package.

This script creates __init__.py files that re-export all protobuf classes without requiring
knowledge of specific _pb2 file names, enabling clean imports like:
    from opensearch.protobufs.schemas import BulkRequest, GlobalParams
    from opensearch.protobufs.services import DocumentServiceStub

EXPECTED FILE STRUCTURE:
========================
opensearch/
├── __init__.py                          # "# OpenSearch Protobufs Python Package"
└── protobufs/
    ├── __init__.py                      # "# OpenSearch Protobufs"
    ├── schemas/
    │   ├── __init__.py                  # Generated schemas re-exports
    │   ├── common_pb2.py                # Generated protobuf messages
    │   ├── common_pb2.pyi               # Type hints
    │   ├── document_pb2.py              # Generated protobuf messages
    │   ├── document_pb2.pyi             # Type hints
    │   ├── search_pb2.py                # Generated protobuf messages
    │   └── search_pb2.pyi               # Type hints
    └── services/
        ├── __init__.py                  # Generated services re-exports
        ├── document_service_pb2.py      # Generated protobuf messages
        ├── document_service_pb2.pyi     # Type hints
        ├── document_service_pb2_grpc.py # Generated gRPC stubs
        ├── search_service_pb2.py        # Generated protobuf messages
        ├── search_service_pb2.pyi       # Type hints
        └── search_service_pb2_grpc.py   # Generated gRPC stubs

GENERATED __init__.py CONTENTS:
===============================

schemas/__init__.py:
-------------------
# OpenSearch Protobuf Schemas
# This module provides convenient access to all protobuf message types
# without requiring knowledge of the specific _pb2 module names.
#
# This file is automatically generated by tools/generate_init_files.py
# DO NOT EDIT MANUALLY

# Import all classes from the generated modules
from .common_pb2 import *
from .document_pb2 import *
from .search_pb2 import *

services/__init__.py:
--------------------
# OpenSearch Protobuf Services
# This module provides convenient access to all gRPC service stubs
# without requiring knowledge of the specific _pb2 module names.
#
# This file is automatically generated by tools/generate_init_files.py
# DO NOT EDIT MANUALLY

# Import all classes from the generated service modules
from .document_service_pb2 import *
from .search_service_pb2 import *
from .document_service_pb2_grpc import *
from .search_service_pb2_grpc import *

USAGE EXAMPLES:
===============
# Clean imports without _pb2 suffixes:
from opensearch.protobufs.schemas import BulkRequest, GlobalParams, SearchRequest
from opensearch.protobufs.services import DocumentServiceStub, SearchServiceStub

# All protobuf classes, gRPC stubs, servicers, and internal classes are available
# No filtering is applied - users get complete access to all generated code

"""

import os
import sys
import re
import logging
from pathlib import Path
from typing import List, Tuple, Set

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


def extract_services_from_proto(proto_file: Path) -> List[str]:
    """
    Extract service definitions from a .proto file.

    Args:
        proto_file: Path to the .proto file

    Returns:
        List of service names
    """
    services = []

    try:
        with open(proto_file, 'r', encoding='utf-8') as f:
            content = f.read()

        # Extract service definitions
        # Matches: service ServiceName {
        service_pattern = r'^service\s+([A-Z][a-zA-Z0-9_]*)\s*\{'
        services = re.findall(service_pattern, content, re.MULTILINE)

        logger.debug(f"Extracted from {proto_file.name}: {len(services)} services")

    except Exception as e:
        logger.error(f"Failed to read {proto_file}: {e}")

    return sorted(set(services))


def extract_definitions_from_proto(proto_file: Path) -> Tuple[List[str], List[str]]:
    """
    Extract message and enum definitions from a .proto file.

    Args:
        proto_file: Path to the .proto file

    Returns:
        Tuple of (messages, enums) lists
    """
    messages = []
    enums = []

    try:
        with open(proto_file, 'r', encoding='utf-8') as f:
            content = f.read()

        # Extract message definitions
        # Matches: message MessageName {
        message_pattern = r'^message\s+([A-Z][a-zA-Z0-9_]*)\s*\{'
        messages = re.findall(message_pattern, content, re.MULTILINE)

        # Extract enum definitions
        # Matches: enum EnumName {
        enum_pattern = r'^enum\s+([A-Z][a-zA-Z0-9_]*)\s*\{'
        enums = re.findall(enum_pattern, content, re.MULTILINE)

        logger.debug(f"Extracted from {proto_file.name}: {len(messages)} messages, {len(enums)} enums")

    except Exception as e:
        logger.error(f"Failed to read {proto_file}: {e}")

    return sorted(set(messages)), sorted(set(enums))


def generate_schemas_init(schemas_output_dir: str, output_file: str) -> List[str]:
    """Generate __init__.py for schemas package using simple approach."""

    schemas_path = Path(schemas_output_dir)
    if not schemas_path.exists():
        logger.error(f"Schemas directory not found: {schemas_path}")
        return []

    # Find all _pb2.py files to determine what to import
    pb2_files = list(schemas_path.glob("*_pb2.py"))

    # For simplicity, we'll import everything and let Python handle the exports
    # This avoids the complexity of parsing proto files or dynamic imports

    # Generate the __init__.py content
    content = '''# OpenSearch Protobuf Schemas
# This module provides convenient access to all protobuf message types
# without requiring knowledge of the specific _pb2 module names.
#
# This file is automatically generated by tools/generate_init_files.py
# DO NOT EDIT MANUALLY

# Import all classes from the generated modules
'''

    # Add imports for each _pb2 file
    for pb2_file in sorted(pb2_files):
        module_name = pb2_file.stem  # e.g., "document_pb2"
        content += f"from .{module_name} import *\n"

    # Write the file atomically
    output_path = Path(output_file)
    temp_file = output_path.with_suffix(f"{output_path.suffix}.tmp")

    try:
        with open(temp_file, 'w', encoding='utf-8') as f:
            f.write(content)
        temp_file.replace(output_path)

        logger.info(f"Generated {output_file} with all available exports")
        return ["*"]  # Indicates all exports are available

    except Exception as e:
        logger.error(f"Failed to write {output_file}: {e}")
        if temp_file.exists():
            temp_file.unlink()
        return []


def generate_services_init(services_dir: str, output_file: str) -> bool:
    """Generate __init__.py for services package with dynamic service discovery."""

    services_path = Path(services_dir)
    if not services_path.exists():
        logger.error(f"Services directory not found: {services_path}")
        return False

    # Find service files (look for _pb2.py and _pb2_grpc.py files)
    pb2_files = [f for f in services_path.glob("*_pb2.py") if not f.name.endswith("_grpc.py")]
    grpc_files = list(services_path.glob("*_pb2_grpc.py"))

    # Dynamically discover services from file names
    all_services = set()
    for grpc_file in grpc_files:
        # Extract service name from filename: document_service_pb2_grpc.py -> DocumentService
        service_name = grpc_file.stem.replace("_pb2_grpc", "").replace("_", " ").title().replace(" ", "")
        all_services.add(service_name)

    all_services = sorted(all_services)

    content = '''# OpenSearch Protobuf Services
# This module provides convenient access to all gRPC service stubs
# without requiring knowledge of the specific _pb2 module names.
#
# This file is automatically generated by tools/generate_init_files.py
# DO NOT EDIT MANUALLY

# Import all classes from the generated service modules
'''

    # Add imports
    for pb2_file in sorted(pb2_files):
        module_name = pb2_file.stem
        content += f"from .{module_name} import *\n"

    for grpc_file in sorted(grpc_files):
        module_name = grpc_file.stem
        content += f"from .{module_name} import *\n"


    # Write the file atomically
    output_path = Path(output_file)
    temp_file = output_path.with_suffix(f"{output_path.suffix}.tmp")

    try:
        with open(temp_file, 'w', encoding='utf-8') as f:
            f.write(content)
        temp_file.replace(output_path)

        logger.info(f"Generated {output_file}")
        return True

    except Exception as e:
        logger.error(f"Failed to write {output_file}: {e}")
        if temp_file.exists():
            temp_file.unlink()
        return False


def main():
    """Main function - reads .proto files directly for service discovery."""
    if len(sys.argv) != 3:
        logger.error("Usage: generate_init_files.py <schemas_output_dir> <services_output_dir>")
        logger.info("Note: This version reads from protos/schemas/ and protos/services/ directories")
        sys.exit(1)

    schemas_output_dir = sys.argv[1]  # Where to write schemas __init__.py
    services_output_dir = sys.argv[2]  # Where to write services __init__.py

    success = True

    # Generate schemas __init__.py by reading .proto files
    try:
        schemas_init = os.path.join(schemas_output_dir, "__init__.py")
        result = generate_schemas_init(schemas_output_dir, schemas_init)
        if not result:
            logger.error("Failed to generate schemas init file")
            success = False
    except Exception as e:
        logger.error(f"Error generating schemas init: {e}")
        success = False

    # Generate services __init__.py
    try:
        services_init = os.path.join(services_output_dir, "__init__.py")
        if not generate_services_init(services_output_dir, services_init):
            logger.error("Failed to generate services init file")
            success = False
    except Exception as e:
        logger.error(f"Error generating services init: {e}")
        success = False

    # Generate parent __init__.py files
    try:
        protobufs_dir = os.path.dirname(schemas_output_dir)
        if protobufs_dir and os.path.basename(protobufs_dir) == "protobufs":
            protobufs_init = os.path.join(protobufs_dir, "__init__.py")
            with open(protobufs_init, 'w') as f:
                f.write("# OpenSearch Protobufs\n")

            opensearch_dir = os.path.dirname(protobufs_dir)
            if opensearch_dir and os.path.basename(opensearch_dir) == "opensearch":
                opensearch_init = os.path.join(opensearch_dir, "__init__.py")
                with open(opensearch_init, 'w') as f:
                    f.write("# OpenSearch Protobufs Python Package\n")
    except Exception as e:
        logger.error(f"Error generating parent init files: {e}")
        success = False

    if success:
        logger.info("✅ All __init__.py files generated successfully!")
        sys.exit(0)
    else:
        logger.error("❌ Some errors occurred during generation")
        sys.exit(1)


if __name__ == "__main__":
    main()
