name: Build OpenSearch Protobufs JAVA Artifact JARs

on:
  pull_request:

jobs:
  build-protobufs-java:
    strategy:
      matrix:
        java:
          - 21
          - 25
    runs-on: ubuntu-latest
    if: github.repository == 'opensearch-project/opensearch-protobufs'

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          distribution: temurin # Temurin is a distribution of adoptium
          java-version: ${{ matrix.java }}
      - name: build protobufs java
        run: ./tools/java/package_proto_jar.sh -c true
