name: Build and Publish Snapshots to Maven

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  build-and-publish-snapshots:
    runs-on: ubuntu-latest
    if: github.repository == 'opensearch-project/opensearch-protobufs'
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin # Temurin is a distribution of adoptium
          java-version: 21

      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          MAVEN_SNAPSHOTS_S3_REPO: op://opensearch-infra-secrets/maven-snapshots-s3/repo
          MAVEN_SNAPSHOTS_S3_ROLE: op://opensearch-infra-secrets/maven-snapshots-s3/role

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ env.MAVEN_SNAPSHOTS_S3_ROLE }}
          aws-region: us-east-1

      - name: publish snapshots to maven
        run: |
          ./tools/java/package_proto_jar.sh -c true
          ./gradlew publishCreatePublicationToSnapshotsRepository
