name: Delete merged branch of the auto-pr-branch PRs
on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.repository == 'opensearch-project/opensearch-protobufs' && github.event.pull_request.head.ref = 'auto-pr-branch'
    steps:
    - name: Delete merged branch
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.git.deleteRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `heads/${context.payload.pull_request.head.ref}`,
          })
